version: '3.9'

services:
 web:
  build:
    context: .
  container_name: architect-website
  ports:
   - 5173:5173
  environment:
      - CHOKIDAR_USEPOLLING=true
  volumes:
   - .:/architect
   - /architect/node_modules